<?php

$result_city=mysql_query("SELECT city FROM emission_dealer");
if(mysql_num_rows($result_city) > 0)
	{
		$finalResult="";
	 	while($rows = mysql_fetch_array($result_city))
		{
			if($finalResult=="")
				$finalResult="<option value='".$rows['city']."'>".$rows['city']."</option>";
			else
				$finalResult.="<option value='".$rows['city']."'>".$rows['city']."</option>";
		}
		echo $finalResult;
	}
/*
echo "<option value='Agra'>Agra</option>
<option value='Ahmedabad'>Ahmedabad</option>
<option value='Ahmednagar'>Ahmednagar</option>
<option value='Aizwal'>Aizwal</option>
<option value='Ajmer'>Ajmer</option>
<option value='Akola'>Akola</option>
<option value='Aligarh'>Aligarh</option>
<option value='Allahabad'>Allahabad</option>
<option value='Alwar'>Alwar</option>
<option value='Ambattur'>Ambattur</option>
<option value='Ambernath'>Ambernath</option>
<option value='Amravati'>Amravati</option>
<option value='Amritsar'>Amritsar</option>
<option value='Anantapur'>Anantapur</option>
<option value='Arrah'>Arrah</option>
<option value='Asansol'>Asansol</option>
<option value='Aurangabad'>Aurangabad</option>
<option value='Avadi'>Avadi</option>
<option value='Bally'>Bally</option>
<option value='Bangalore'>Bangalore</option>
<option value='Baranagar'>Baranagar</option>
<option value='Bardhaman'>Bardhaman</option>
<option value='Bareilly'>Bareilly</option>
<option value='Bathinda'>Bathinda</option>
<option value='Belgaum'>Belgaum</option>
<option value='Bellary'>Bellary</option>
<option value='Bhagalpur'>Bhagalpur</option>
<option value='Bharatpur'>Bharatpur</option>
<option value='Bhatpara'>Bhatpara</option>
<option value='Bhavnagar'>Bhavnagar</option>
<option value='Bhilai'>Bhilai</option>
<option value='Bhilwara'>Bhilwara</option>
<option value='Bhiwandi'>Bhiwandi</option>
<option value='Bhopal'>Bhopal</option>
<option value='Bhubaneswar'>Bhubaneswar</option>
<option value='Bidar'>Bidar</option>
<option value='Bidhan Nagar'>Bidhan Nagar</option>
<option value='Bihar Sharif'>Bihar Sharif</option>
<option value='Bijapur'>Bijapur</option>
<option value='Bikaner'>Bikaner</option>
<option value='Bilaspur'>Bilaspur</option>
<option value='Bokaro'>Bokaro</option>
<option value='Brahmapur'>Brahmapur</option>
<option value='Burhanpur'>Burhanpur</option>
<option value='Chandigarh'>Chandigarh</option>
<option value='Chandrapur'>Chandrapur</option>
<option value='Chennai'>Chennai</option>
<option value='Coimbatore'>Coimbatore</option>
<option value='Cuttack'>Cuttack</option>
<option value='Darbhanga'>Darbhanga</option>
<option value='Davanagere'>Davanagere</option>
<option value='Dehradun'>Dehradun</option>
<option value='Delhi'>Delhi</option>
<option value='Deoli'>Deoli</option>
<option value='Dewas'>Dewas</option>
<option value='Dhanbad'>Dhanbad</option>
<option value='Dhule'>Dhule</option>
<option value='Durg'>Durg</option>
<option value='Durgapur'>Durgapur</option>
<option value='Erode'>Erode</option>
<option value='Etawah'>Etawah</option>
<option value='Faridabad'>Faridabad</option>
<option value='Farrukhabad'>Farrukhabad</option>
<option value='Firozabad'>Firozabad</option>
<option value='Gandhinagar'>Gandhinagar</option>
<option value='Gaya'>Gaya</option>
<option value='Ghaziabad'>Ghaziabad</option>
<option value='Gopalpur'>Gopalpur</option>
<option value='Gorakhpur'>Gorakhpur</option>
<option value='Gulbarga'>Gulbarga</option>
<option value='Guntur'>Guntur</option>
<option value='Guwahati'>Guwahati</option>
<option value='Gwalior'>Gwalior</option>
<option value='Hapur'>Hapur</option>
<option value='Hisar'>Hisar</option>
<option value='Hosapete'>Hosapete</option>
<option value='Howrah'>Howrah</option>
<option value='Hubballi-Dharwad'>Hubballi-Dharwad</option>
<option value='Hyderabad'>Hyderabad</option>
<option value='Ichalkaranji'>Ichalkaranji</option>
<option value='Imphal'>Imphal</option>
<option value='Indore'>Indore</option>
<option value='Jabalpur'>Jabalpur</option>
<option value='Jaipur'>Jaipur</option>
<option value='Jalandhar'>Jalandhar</option>
<option value='Jalgaon'>Jalgaon</option>
<option value='Jalna'>Jalna</option>
<option value='Jammu'>Jammu</option>
<option value='Jamnagar'>Jamnagar</option>
<option value='Jamshedpur'>Jamshedpur</option>
<option value='Jhansi'>Jhansi</option>
<option value='Jodhpur'>Jodhpur</option>
<option value='Kakinada'>Kakinada</option>
<option value='Kalyan-Dombivali'>Kalyan-Dombivali</option>
<option value='Kamarhati'>Kamarhati</option>
<option value='Kanpur'>Kanpur</option>
<option value='Karimnagar'>Karimnagar</option>
<option value='Cochin'>Cochin</option>
<option value='Kolhapur'>Kolhapur</option>
<option value='Kolkata'>Kolkata</option>
<option value='Kollam'>Kollam</option>
<option value='Korba'>Korba</option>
<option value='Kota'>Kota</option>
<option value='Calicut'>Calicut</option>
<option value='Kulti'>Kulti</option>
<option value='Kurnool'>Kurnool</option>
<option value='Latur'>Latur</option>
<option value='Loni'>Loni</option>
<option value='Lucknow'>Lucknow</option>
<option value='Ludhiana'>Ludhiana</option>
<option value='Madurai'>Madurai</option>
<option value='Maheshtala'>Maheshtala</option>
<option value='Malegaon'>Malegaon</option>
<option value='Mangalore'>Mangalore</option>
<option value='Mathura'>Mathura</option>
<option value='Mau'>Mau</option>
<option value='Meerut'>Meerut</option>
<option value='Mira-Bhayandar'>Mira-Bhayandar</option>
<option value='Mirzapur'>Mirzapur</option>
<option value='Moradabad'>Moradabad</option>
<option value='Mumbai'>Mumbai</option>
<option value='Muzaffarnagar'>Muzaffarnagar</option>
<option value='Muzaffarpur'>Muzaffarpur</option>
<option value='Mysore'>Mysore</option>
<option value='Nagpur'>Nagpur</option>
<option value='Naihati'>Naihati</option>
<option value='Nanded'>Nanded</option>
<option value='Nangloi Jat'>Nangloi Jat</option>
<option value='Nashik'>Nashik</option>
<option value='Navi Mumbai'>Navi Mumbai</option>
<option value='Nellore'>Nellore</option>
<option value='New Delhi'>New Delhi</option>
<option value='Nizamabad'>Nizamabad</option>
<option value='Noida'>Noida</option>
<option value='North Dumdum'>North Dumdum</option>
<option value='Ozhukarai'>Ozhukarai</option>
<option value='Pali'>Pali</option>
<option value='Panihati'>Panihati</option>
<option value='Panipat'>Panipat</option>
<option value='Panvel'>Panvel</option>
<option value='Parbhani'>Parbhani</option>
<option value='Patiala'>Patiala</option>
<option value='Patna'>Patna</option>
<option value='Pimpri-Chinchwad'>Pimpri-Chinchwad</option>
<option value='Pune'>Pune</option>
<option value='Puri'>Puri</option>
<option value='Purnia'>Purnia</option>
<option value='Raichur'>Raichur</option>
<option value='Raipur'>Raipur</option>
<option value='Rajahmundry'>Rajahmundry</option>
<option value='Rajkot'>Rajkot</option>
<option value='Rajpur Sonarpur'>Rajpur Sonarpur</option>
<option value='Ramagundam'>Ramagundam</option>
<option value='Rampur'>Rampur</option>
<option value='Ranchi'>Ranchi</option>
<option value='Ratlam'>Ratlam</option>
<option value='Rewa'>Rewa</option>
<option value='Rohtak'>Rohtak</option>
<option value='Sagar'>Sagar</option>
<option value='Saharanpur'>Saharanpur</option>
<option value='Salem'>Salem</option>
<option value='Sangli-Miraj & Kupwad'>Sangli-Miraj & Kupwad</option>
<option value='Satna'>Satna</option>
<option value='Secunderabad'>Secunderabad</option>
<option value='Serampore'>Serampore</option>
<option value='Shahjahanpur'>Shahjahanpur</option>
<option value='Shimoga'>Shimoga</option>
<option value='Siliguri'>Siliguri</option>
<option value='Singrauli'>Singrauli</option>
<option value='Solapur'>Solapur</option>
<option value='Sonipat'>Sonipat</option>
<option value='South Dumdum'>South Dumdum</option>
<option value='Sri Ganganagar'>Sri Ganganagar</option>
<option value='Srinagar'>Srinagar</option>
<option value='Surat'>Surat</option>
<option value='Thane'>Thane</option>
<option value='Thiruvananthapuram'>Thiruvananthapuram</option>
<option value='Thrissur'>Thrissur</option>
<option value='Tiruchirappalli'>Tiruchirappalli</option>
<option value='Tirunelveli'>Tirunelveli</option>
<option value='Tirupati'>Tirupati</option>
<option value='Tirupur'>Tirupur</option>
<option value='Tiruvottiyur'>Tiruvottiyur</option>
<option value='Tumkur'>Tumkur</option>
<option value='Udaipur'>Udaipur</option>
<option value='Ujjain'>Ujjain</option>
<option value='Ulhasnagar'>Ulhasnagar</option>
<option value='Uluberia'>Uluberia</option>
<option value='Vadodara'>Vadodara</option>
<option value='Varanasi'>Varanasi</option>
<option value='Vasai-Virar'>Vasai-Virar</option>
<option value='Vijayawada'>Vijayawada</option>
<option value='Visakhapatnam'>Visakhapatnam</option>
<option value='Warangal'>Warangal</option>";*/
?>