<?php
if($_SERVER['HTTP_HOST']=="localhost")
{
define("host","Gv/FQqMa7d7DTcjp1mBNMjji0qOxxPTNA8gmKRmtafs=");
define("user_name","lTbAwyrbroZY86hs2ZUbSyC4JLD8EeBxRG4+3rfaquY=");
define("passwrd","jnoJp28IyDSORfs+CbPB4pswTX+7Qunn7UpViPVgzmQ=");
define("dbname","9cMn1LeZe+V5gnsemaiFK1uesa190kMOzn2Q8VJOqS4=");
}
else
{
define("host","Gv/FQqMa7d7DTcjp1mBNMjji0qOxxPTNA8gmKRmtafs=");
define("user_name","lTbAwyrbroZY86hs2ZUbSyC4JLD8EeBxRG4+3rfaquY=");
define("passwrd","lTbAwyrbroZY86hs2ZUbSyC4JLD8EeBxRG4+3rfaquY=");
define("dbname","lTbAwyrbroZY86hs2ZUbSyC4JLD8EeBxRG4+3rfaquY=");
}
?>